apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mc-http-server.fullname" . }}
  labels:
    app: {{ template "mc-http-server.name" . }}
    chart: {{ template "mc-http-server.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data: |
{{ .Values.mc-http-server.config | .ToJson | nindent 2 }}
