codecov:
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "80...100"
  # COMMENT:Can set project coverage target here
  # status:
  #   project:
  #     default:
  #       target: 80%
  #       threshold: 5%
  #   patch:
  #     default:
  #       target: 80%

parsers:
  gcov:
    branch_detection:
      conditional: yes

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "**/node_modules/**"
  - "**/coverage/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.next/**"
  - "**/cypress/videos/**"
  - "**/cypress/screenshots/**"
  - "**/*.test.js"
  - "**/*.test.ts"
  - "**/*.spec.js"
  - "**/*.spec.ts"
  - "**/test/**"
  - "**/tests/**"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/stories/**"
  - "**/*.stories.*"
  - "**/playground/**"
  - "**/examples/**"
  - "**/docs/**"
  - "**/.github/**"
  - "**/.vscode/**"
  - "**/scripts/**"
  - "**/config/**"
