codecov:
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "80...100"
  # COMMENT:Can set project coverage target here
  # status:
  #   project:
  #     default:
  #       target: 80%
  #       threshold: 5%
  #   patch:
  #     default:
  #       target: 80%

parsers:
  gcov:
    branch_detection:
      conditional: yes

comment:
  layout: "reach,diff,flags,components,footer"
  behavior: default
  require_changes: no

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: application_components
      name: Application Components
      paths:
        - "packages/application-components/**"
      statuses:
        - type: project
          target: auto
        - type: patch
    - component_id: application_shell
      name: Application Shell
      paths:
        - "packages/application-shell/**"
      statuses:
        - type: project
          target: auto
        - type: patch
    - component_id: application_shell_connectors
      name: Application Shell Connectors
      paths:
        - "packages/application-shell-connectors/**"
      statuses:
        - type: project
          target: auto
        - type: patch

ignore:
  - "node_modules/**"
  - "coverage/**"
  - "cypress-coverage/**"
  - ".nyc_output/**"
  - ".cache/**"
  - "dist/**"
  - "build/**"
  - ".next/**"
  - "cypress/videos/**"
  - "cypress/screenshots/**"
  - "**/*.test.js"
  - "**/*.test.ts"
  - "**/*.spec.js"
  - "**/*.spec.ts"
  - "test/**"
  - "tests/**"
  - "__tests__/**"
  - "__mocks__/**"
  - "stories/**"
  - "**/*.stories.*"
  - "playground/**"
  - "examples/**"
  - "website/**"
  - "website-components-playground/**"
  - "visual-testing-app/**"
  - "test-data/**"
  - "graphql-test-utils/**"
  - "custom-views-templates/**"
  - "application-templates/**"
  - "@types-extensions/**"
  - "@types/**"
  - "packages-backend/**"
  - "patches/**"
  - ".changeset/**"
  - ".husky/**"
  - ".yarn/**"
  - "schemas/**"
  - "docs/**"
  - ".github/**"
  - ".vscode/**"
  - "scripts/**"
  - "config/**"
