parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 8
  sourceType: module
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:jest/recommended
  - plugin:react/recommended
  - plugin:testing-library-react/recommended
  - prettier
  - prettier/react
  - prettier/@typescript-eslint
plugins:
  - import
  - jest
  - jsx-a11y
  - prettier
  - react
  - react-hooks
  - graphql
  - '@typescript-eslint/eslint-plugin'
rules:
  '@typescript-eslint/camelcase': 0
  '@typescript-eslint/consistent-type-definitions': 0
  '@typescript-eslint/no-explicit-any': 2
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/unbound-method': 0
  react/jsx-tag-spacing: 0
  import/no-extraneous-dependencies: 0
  import/no-named-as-default: 0
  import/no-unresolved: 2
  'react-hooks/rules-of-hooks': 'error'
  'react-hooks/exhaustive-deps': 'warn'
  graphql/template-strings:
    - error
    - env: literal
settings:
  react:
    version: 'detect'
  import/ignore:
    - /test-utils/
    - test-utils$
    - test-utils\.js$
  import/parsers:
    '@typescript-eslint/parser': ['.ts', '.tsx']
  import/resolver:
    eslint-import-resolver-typescript: true
    typescript: {}
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']
overrides:
  - files: ['*.spec.js']
    rules:
      'react/display-name': 0
  - files: ['*.visualroute.js']
    rules:
      'import/extensions':
        [
          2,
          {
            ignore:
              [
                '@local-build/application-components',
                '@local-build/react-notifications',
              ],
          },
        ]
      'import/no-unresolved':
        [
          2,
          {
            ignore:
              [
                '@local-build/application-components',
                '@local-build/react-notifications',
              ],
          },
        ]
      'react/display-name': 0
  - files: ['*.visualspec.js']
    globals:
      page: true
      HOST: true
  - files: ['*.js']
    rules:
      '@typescript-eslint/explicit-function-return-type': 0
  - files: ['*.ts', '*.tsx']
    rules:
      '@typescript-eslint/ban-ts-ignore': 0
      '@typescript-eslint/explicit-function-return-type': 0
      '@typescript-eslint/explicit-member-accessibility':
        [2, { accessibility: 'no-public' }]
      '@typescript-eslint/no-require-imports': 0
      '@typescript-eslint/promise-function-async': 0
      react/prop-types: 0
  #     import/extensions:
  #       - error
  #       - always
  #       - js: never
  #       - mjs: never
  #       - ts: never
  #       - tsx: never
