projects:
  mc:
    schema:
      - '${MC_API_URL}':
          headers:
            X-Graphql-Target: mc
    documents: '**/*.mc.graphql'
    extensions:
      codegen:
        generates:
          schemas/mc.json:
            plugins:
              - introspection
          '@types-extensions/graphql-mc.d.ts':
            plugins:
              - add:
                  content: /* THIS IS A GENERATED FILE */
              - add:
                  content: /* eslint-disable import/no-duplicates */
              - typescript-graphql-files-modules
          packages/application-shell-connectors/src/types/generated/mc.ts:
            config:
              addUnderscoreToArgsType: true
              avoidOptionals: true
              maybeValue: T | undefined
              typesPrefix: T
            plugins:
              - typescript
              - typescript-operations
          packages/application-shell/src/types/generated/mc.ts:
            config:
              addUnderscoreToArgsType: true
              avoidOptionals: true
              maybeValue: T | undefined
              typesPrefix: T
            plugins:
              - typescript
              - typescript-operations
        hooks:
          afterAllFileWrite:
            - prettier --write
  ctp:
    schema:
      - '${MC_API_URL}':
          headers:
            Cookie: mcAccessToken=${MC_ACCESS_TOKEN}
            X-Graphql-Target: ctp
            X-Project-Key: ${CTP_PROJECT_KEY}
    documents: '**/*.ctp.graphql'
    extensions:
      codegen:
        generates:
          schemas/ctp.json:
            plugins:
              - introspection
          '@types-extensions/graphql-ctp.d.ts':
            schema: schemas/ctp.json
            documents: packages/**/src/**/*.ctp.graphql
            plugins:
              - add:
                  content: '/* THIS IS A GENERATED FILE */'
              - add:
                  content: '/* eslint-disable import/no-duplicates */'
              - typescript-graphql-files-modules
          packages/application-components/src/types/generated/ctp.ts:
            schema: schemas/ctp.json
            documents: packages/**/src/**/*.ctp.graphql
            plugins:
              - typescript
              - typescript-operations
            config:
              typesPrefix: T
              addUnderscoreToArgsType: true
              avoidOptionals: true
              maybeValue: T | undefined
              scalars:
                Long: number
                DateTime: string
                Country: string
                Locale: string
                Date: string
                Json: '{ [key: string]: unknown }'
                Currency: string
                KeyReferenceInput: string
                SearchFilter: string
                SearchSort: string
                YearMonth: string
                BigDecimal: string
                Time: string
                Set: 'unknown[]'
          packages/application-shell/src/types/generated/ctp.ts:
            schema: schemas/ctp.json
            documents: packages/**/src/**/*.ctp.graphql
            plugins:
              - typescript
              - typescript-operations
            config:
              typesPrefix: T
              addUnderscoreToArgsType: true
              avoidOptionals: true
              maybeValue: T | undefined
              scalars:
                Long: number
                DateTime: string
                Country: string
                Locale: string
                Date: string
                Json: '{ [key: string]: unknown }'
                Currency: string
                KeyReferenceInput: string
                SearchFilter: string
                SearchSort: string
                YearMonth: string
                BigDecimal: string
                Time: string
                Set: 'unknown[]'
        hooks:
          afterAllFileWrite:
            - prettier --write
  settings:
    schema:
      - '${MC_API_URL}':
          headers:
            Cookie: mcAccessToken=${MC_ACCESS_TOKEN}
            X-Graphql-Target: settings
    documents: '**/*.settings.graphql'
    extensions:
      codegen:
        generates:
          schemas/settings.json:
            plugins:
              - introspection
          '@types-extensions/graphql-settings.d.ts':
            schema: schemas/settings.json
            documents: packages/**/src/**/*.settings.graphql
            plugins:
              - add:
                  content: '/* THIS IS A GENERATED FILE */'
              - add:
                  content: '/* eslint-disable import/no-duplicates */'
              - typescript-graphql-files-modules
          packages/application-shell/src/types/generated/settings.ts:
            schema: schemas/settings.json
            documents: packages/**/src/**/*.settings.graphql
            plugins:
              - typescript
              - typescript-operations
            config:
              typesPrefix: T
              addUnderscoreToArgsType: true
              avoidOptionals: true
              maybeValue: T | undefined
              scalars:
                DateTime: string
                Json: '{ [key: string]: unknown }'
          packages/application-shell-connectors/src/types/generated/settings.ts:
            schema: schemas/settings.json
            documents: packages/**/src/**/*.settings.graphql
            plugins:
              - typescript
              - typescript-operations
            config:
              typesPrefix: T
              addUnderscoreToArgsType: true
              avoidOptionals: true
              maybeValue: T | undefined
              scalars:
                DateTime: string
                Json: '{ [key: string]: unknown }'
  proxy:
    schema: '${MC_PROXY_URL}'
    documents: '**/*.proxy.graphql'
    extensions:
      codegen:
        generates:
          schemas/proxy.json:
            plugins:
              - introspection
          '@types-extensions/graphql-proxy.d.ts':
            schema: schemas/proxy.json
            documents: packages/**/src/**/*.proxy.graphql
            plugins:
              - add:
                  content: '/* THIS IS A GENERATED FILE */'
              - add:
                  content: '/* eslint-disable import/no-duplicates */'
              - typescript-graphql-files-modules
          packages/application-shell/src/types/generated/proxy.ts:
            schema: schemas/proxy.json
            documents: packages/**/src/**/*.proxy.graphql
            plugins:
              - typescript
              - typescript-operations
            config:
              typesPrefix: T
              addUnderscoreToArgsType: true
              avoidOptionals: true
              maybeValue: T | undefined
