nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall.cjs
    spec: "https://raw.githubusercontent.com/gravitywelluk/yarn-plugin-postinstall/master/bundles/%40yarnpkg/plugin-postinstall.js"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

packageExtensions:
  "@vercel/build-utils@^2.15.0":
    dependencies:
      "@vercel/frameworks": "^0.7.0"
      "@vercel/routing-utils": "^1.13.0"
  "debug@^4.3.3":
    dependencies:
      "@types/debug": "^4.1.7"
  "lmdb@^2.5.3":
    dependencies:
      "cbor-x": "^1.3.1"

postinstall: ./scripts/postinstall.sh

yarnPath: .yarn/releases/yarn-3.2.1.cjs
