[build]
  command = "yarn build && yarn --cwd website build"
  publish = "website/public"

[build.environment]
  YARN_FLAGS = "--pure-lockfile"
  YARN_VERSION = "1.15.2"
  GATSBY_CPU_COUNT = "logical_cores"
