[build]
  command = "yarn build && yarn --cwd website build && yarn --cwd website-components-playground build"
  publish = "website/public"

[build.environment]
  YARN_FLAGS = "--frozen-lockfile"
  YARN_VERSION = "1.19.0"
  GATSBY_CPU_COUNT = "logical_cores"
