/* eslint-disable prettier/prettier */
// This file was automatically generated by json-schema-to-typescript.
// DO NOT MODIFY IT BY HAND. Instead, modify the source custom-view.schema.json file and run the build:schemas npm script.

export type CspDirective = string[];

export interface JSONSchemaForCustomViewConfigurationFiles {
  /**
   * See https://docs.commercetools.com/
   */
  name: string;
  /**
   * See https://docs.commercetools.com/
   */
  description?: string;
  /**
   * See https://docs.commercetools.com/
   */
  cloudIdentifier: string;
  /**
   * See https://docs.commercetools.com/
   */
  mcApiUrl?: string;
  /**
   * See https://docs.commercetools.com/
   */
  oAuthScopes: {
    /**
     * See https://docs.commercetools.com/
     */
    view: string[];
    /**
     * See https://docs.commercetools.com/
     */
    manage: string[];
  };
  /**
   * See https://docs.commercetools.com/
   */
  additionalOAuthScopes?: {
    /**
     * See https://docs.commercetools.com/
     */
    name: string;
    /**
     * See https://docs.commercetools.com/
     */
    view: string[];
    /**
     * See https://docs.commercetools.com/
     */
    manage: string[];
  }[];
  /**
   * See https://docs.commercetools.com/
   */
  env: {
    development: {
      /**
       * See https://docs.commercetools.com/
       */
      initialProjectKey: string;
      teamId?: string;
    };
    production: {
      /**
       * See https://docs.commercetools.com/
       */
      customViewId: string;
      /**
       * See https://docs.commercetools.com/
       */
      url: string;
      /**
       * See https://docs.commercetools.com/
       */
      cdnUrl?: string;
    };
  };
  /**
   * See https://docs.commercetools.com/
   */
  additionalEnv?: {
    [k: string]: unknown;
  };
  /**
   * See https://docs.commercetools.com/
   */
  headers?: {
    /**
     * See https://docs.commercetools.com/
     */
    csp?: {
      'connect-src': CspDirective;
      'font-src'?: CspDirective;
      'img-src'?: CspDirective;
      'script-src'?: CspDirective;
      'style-src'?: CspDirective;
      'frame-src'?: CspDirective;
    };
    /**
     * See https://docs.commercetools.com/
     */
    permissionsPolicies?: {
      [k: string]: unknown;
    };
    /**
     * See https://docs.commercetools.com/
     */
    strictTransportSecurity?: ('includeSubDomains' | 'preload')[];
  };
  [k: string]: unknown;
}
