const permissions = {
  ManageProject: 'ManageProject',
  ManageCustomers: 'ManageCustomers',
  ManageOrders: 'ManageOrders',
  ManageProducts: 'ManageProducts',
  ManageOauthClients: 'ManageOauthClients',
  ManageStates: 'ManageStates',
  ManageTypes: 'ManageTypes',
  ViewCustomers: 'ViewCustomers',
  ViewOrders: 'ViewOrders',
  ViewProducts: 'ViewProducts',
  ViewStates: 'ViewStates',
  ViewTypes: 'ViewTypes',
  AddCategory: 'AddCategory',
  AddCustomer: 'AddCustomer',
  AddCustomerGroup: 'AddCustomerGroup',
  AddDiscountCode: 'AddDiscountCode',
  AddDiscounts: 'AddDiscounts',
  AddOrders: 'AddOrders',
  AddPrices: 'AddPrices',
  AddProducts: 'AddProducts',
  DeletePrices: 'DeletePrices',
  DeleteProducts: 'DeleteProducts',
  EditPrices: 'EditPrices',
  PublishProducts: 'PublishProducts',
  UnpublishProducts: 'UnpublishProducts',
  ViewCartDiscounts: 'ViewCartDiscounts',
  ViewCategories: 'ViewCategories',
  ViewCategoriesSearch: 'ViewCategoriesSearch',
  ViewCustomApplications: 'ViewCustomApplications',
  ViewCustomerGroups: 'ViewCustomerGroups',
  ViewDashboard: 'ViewDashboard',
  ViewDeveloperSettings: 'ViewDeveloperSettings',
  ViewDirectAccess: 'ViewDirectAccess',
  ViewDiscountCodes: 'ViewDiscountCodes',
  ViewDiscounts: 'ViewDiscounts',
  ViewModifiedProducts: 'ViewModifiedProducts',
  ViewPimSearchList: 'ViewPimSearchList',
  ViewProductDiscounts: 'ViewProductDiscounts',
  ViewProductTypes: 'ViewProductTypes',
  ViewProjectSettingsMisc: 'ViewProjectSettingsMisc',
  ViewSettings: 'ViewSettings',
  ViewShippingLists: 'ViewShippingLists',
  ViewProjectSettings: 'ViewProjectSettings',
  ManageProjectSettings: 'ManageProjectSettings',
};

/* eslint-disable import/prefer-default-export */
export { permissions };
