const permissions = {
  ManageProject: 'ManageProject',
  ManageCustomers: 'ManageCustomers',
  ManageOrders: 'ManageOrders',
  ManageProducts: 'ManageProducts',
  ManageOauthClients: 'ManageOauthClients',
  ManageStates: 'ManageStates',
  ManageTypes: 'ManageTypes',
  ViewCustomers: 'ViewCustomers',
  ViewOrders: 'ViewOrders',
  ViewProducts: 'ViewProducts',
  ViewStates: 'ViewStates',
  ViewTypes: 'ViewTypes',
  AddCategory: 'AddCategory',
  AddCustomer: 'AddCustomer',
  AddCustomerGroup: 'AddCustomerGroup',
  AddDiscountCode: 'AddDiscountCode',
  AddOrder: 'AddOrder',
  AddPrice: 'AddPrice',
  AddProduct: 'AddProduct',
  DeletePrice: 'DeletePrice',
  DeleteProduct: 'DeleteProduct',
  EditPrice: 'EditPrice',
  PublishProduct: 'PublishProduct',
  UnpublishProduct: 'UnpublishProduct',
  ViewCartDiscountsList: 'ViewCartDiscountsList',
  ViewCategories: 'ViewCategories',
  ViewCategoriesSearch: 'ViewCategoriesSearch',
  ViewCustomApplications: 'ViewCustomApplications',
  ViewCustomerGroupsList: 'ViewCustomerGroupsList',
  ViewCustomersList: 'ViewCustomersList',
  ViewDashboard: 'ViewDashboard',
  ViewDeveloperSettings: 'ViewDeveloperSettings',
  ViewDirectAccess: 'ViewDirectAccess',
  ViewDiscountCodesList: 'ViewDiscountCodesList',
  ViewDiscounts: 'ViewDiscounts',
  ViewModifiedProducts: 'ViewModifiedProducts',
  ViewOrdersList: 'ViewOrdersList',
  ViewPimSearchList: 'ViewPimSearchList',
  ViewProductDiscountsList: 'ViewProductDiscountsList',
  ViewProductsList: 'ViewProductsList',
  ViewProductTypes: 'ViewProductTypes',
  ViewProjectSettingsMisc: 'ViewProjectSettingsMisc',
  ViewSettings: 'ViewSettings',
  ViewShippingLists: 'ViewShippingLists',
};

/* eslint-disable import/prefer-default-export */
export { permissions };
