const permissions = {
  AddCategories: 'AddCategories',
  AddCustomerGroups: 'AddCustomerGroups',
  AddCustomers: 'AddCustomers',
  AddDiscountCodes: 'AddDiscountCodes',
  AddDiscounts: 'AddDiscounts',
  AddOrders: 'AddOrders',
  AddPrices: 'AddPrices',
  AddProducts: 'AddProducts',
  DeletePrices: 'DeletePrices',
  DeleteProducts: 'DeleteProducts',
  EditPrices: 'EditPrices',
  ManageCustomers: 'ManageCustomers',
  ManageOauthClients: 'ManageOauthClients',
  ManageOrders: 'ManageOrders',
  ManageProducts: 'ManageProducts',
  ManageProject: 'ManageProject',
  ManageProjectSettings: 'ManageProjectSettings',
  ManageStates: 'ManageStates',
  ManageTypes: 'ManageTypes',
  PublishProducts: 'PublishProducts',
  UnpublishProducts: 'UnpublishProducts',
  ViewCartDiscounts: 'ViewCartDiscounts',
  ViewCategories: 'ViewCategories',
  ViewCategoriesList: 'ViewCategoriesList',
  ViewCategoriesSearch: 'ViewCategoriesSearch',
  ViewCustomApplications: 'ViewCustomApplications',
  ViewCustomerGroups: 'ViewCustomerGroups',
  ViewCustomers: 'ViewCustomers',
  ViewCustomersList: 'ViewCustomersList',
  ViewDashboard: 'ViewDashboard',
  ViewDeveloperSettings: 'ViewDeveloperSettings',
  ViewDirectAccess: 'ViewDirectAccess',
  ViewDiscountCodes: 'ViewDiscountCodes',
  ViewDiscounts: 'ViewDiscounts',
  ViewDiscountsList: 'ViewDiscountsList',
  ViewModifiedProducts: 'ViewModifiedProducts',
  ViewOrders: 'ViewOrders',
  ViewOrdersList: 'ViewOrdersList',
  ViewPimSearch: 'ViewPimSearch',
  ViewProductDiscounts: 'ViewProductDiscounts',
  ViewProducts: 'ViewProducts',
  ViewProductsList: 'ViewProductsList',
  ViewProductTypes: 'ViewProductTypes',
  ViewProjectSettings: 'ViewProjectSettings',
  ViewProjectSettingsMisc: 'ViewProjectSettingsMisc',
  ViewSettings: 'ViewSettings',
  ViewShippingLists: 'ViewShippingLists',
  ViewStates: 'ViewStates',
  ViewTypes: 'ViewTypes',
};

/* eslint-disable import/prefer-default-export */
export { permissions };
