name: CI

description: Shared action with basic setup for each job

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        run_install: false

    - name: Setup Node (uses version in .nvmrc)
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: pnpm

    - name: Install dependencies
      run: pnpm install
      env:
        # https://github.com/bahmutov/cypress-gh-action-split-install/blob/ca3916d4e7240ebdc337825d2d78eb354855464b/.github/workflows/tests.yml#L14-L18
        # https://github.com/marketplace/actions/cypress-io#custom-install
        CYPRESS_INSTALL_BINARY: '0'
      shell: bash

    - name: Building packages
      run: pnpm build
      shell: bash
