steps:
  # As this build gets triggered during a release cycle,
  # lerna will push the git tag before publishing the packages
  # to npm, which causes the docker build to fail to install
  # the dependencies (as they are not been fully published yet).
  # Therefore, we try to wait for about 30s before building
  # the docker image, which should give enough time for
  # the lerna release to finish.
  - name: 'ubuntu'
    args: ['sleep', '30']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'eu.gcr.io/$PROJECT_ID/mc-http-server:$TAG_NAME',
        '-t',
        'eu.gcr.io/$PROJECT_ID/mc-http-server:latest',
        './packages/mc-http-server',
      ]
images:
  - 'eu.gcr.io/$PROJECT_ID/mc-http-server:$TAG_NAME'
  - 'eu.gcr.io/$PROJECT_ID/mc-http-server:latest'
