name: After deployments

on: [deployment_status]

jobs:
  link-check:
    name: 'Check links'

    if: github.event.deployment_status.state == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check links
        uses: docker://tennox/linkcheck:2.0.20
        with:
          args: --external --skip-file website/.linkcheckignore.txt ${{ github.event.deployment_status.target_url }}
