name: After deployments

on: [deployment_status]

jobs:
  link-check:
    name: 'Check links'

    if: github.event.deployment_status.state == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check links
        run: |
          ./.linkcheck/releases/2.0.20/linux-x64/linkcheck \
            --external \
            --skip-file .linkcheck/skip_list.txt \
            ${{ github.event.deployment_status.target_url }}
