name: After deployments

on: [deployment_status]

jobs:
  link-check:
    name: 'Check links'

    if: github.event.deployment_status.state == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node (uses version in .nvmrc)
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Check links
        # the docs production domain has to be rewritten to the preview URL to allow new pages to be created without the link checker
        # erroring on the canonical URL of the new page. Known compromise to not find links that point to the absolute production URL
        # but the docs kit is automatically making those a relative URL in authored content so the impact is low.
        run: |
          npx --yes linkinator@3.x \
            --config website/linkinator.remote.config.json \
            --url-rewrite-replace=${{ github.event.deployment_status.target_url }} \
            ${{ github.event.deployment_status.target_url }}
