name: Label Checker

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  check_labels:
    if: github.event_name == 'pull_request'
    name: Prevent merge with blocking labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker@sha256:65e57fd98ba3ab6ca4fcbc5a0aef288dd984ee4ab988f124d83424d19b55b801 # latest as of 2026-07-22
        with:
          none_of: '👁 👨‍🎨 Status: UI/UX Review,🖐 🖐 Status: On Hold,🛑 Status: blocked,🚧 Status: WIP'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
