# This workflow is only for testing.

name: Preview Release on Push

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      # Get GitHub token via the CT Changesets App
      - name: Generate GitHub token (via CT Changesets App)
        id: generate_github_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.CT_CHANGESETS_APP_ID }}
          private_key: ${{ secrets.CT_CHANGESETS_APP_PEM }}
      
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ steps.generate_github_token.outputs.token }}   

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          scope: "@commercetools"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Installing dependencies and building packages
        uses: ./.github/actions/ci
      
      - name: Storing release version for changeset
        id: release_version
        run: echo "VALUE=$(./scripts/print_release_version.sh)" >> $GITHUB_OUTPUT
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.generate_github_token.outputs.token }}

      - name: Publishing preview releases to npm registry
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          git checkout ${{ github.head_ref }}
          pnpm changeset version --snapshot ${BRANCH_NAME}
          pnpm changeset publish --tag ${BRANCH_NAME}
        env:
          GITHUB_TOKEN: ${{ steps.generate_github_token.outputs.token }}