name: Preview Release Request

permissions:
  issues: read
  pull-requests: read
  actions: write
  
on:
  issue_comment:
    types: [created]

jobs:
  validate_preview_request:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '[preview_deployment]')
    runs-on: ubuntu-latest

    steps:
      - name: Get branch of PR
        uses: xt0rted/pull-request-comment-branch@v3
        id: comment-branch

      - name: Validate branch name
        run: |
          if [[ ! "$BRANCH_NAME" =~ ^preview/[a-zA-Z0-9_-]+$ ]]; then
            echo "Ignoring PR because of the branch name. Exiting workflow."
            exit 1
          fi
        env:
          BRANCH_NAME: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Save metadata for next workflow
        run: |
          mkdir -p pr/
          echo "${{ github.event.issue.number }}" > pr/PR_NUMBER
          echo "${{ steps.comment-branch.outputs.head_ref }}" > pr/BRANCH_NAME

      - name: Upload metadata artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-release-metadata
          path: pr/