name: Preview Release Publish

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write

on:
  workflow_run:
    workflows: ["Preview Release Build"]
    types:
      - completed

jobs:
  publish:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      # Get GitHub token via the CT Changesets App
      - name: Generate GitHub token (via CT Changesets App)
        id: generate_github_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.CT_CHANGESETS_APP_ID }}
          private_key: ${{ secrets.CT_CHANGESETS_APP_PEM }}

      - name: Download PR metadata
        uses: actions/download-artifact@v4
        with:
          name: pr-metadata
          path: ./pr-metadata

      - name: Extract PR metadata
        run: |
          echo "PR_NUMBER=$(cat ./pr-metadata/PR_NUMBER)" >> $GITHUB_ENV
          echo "BRANCH_NAME=$(cat ./pr-metadata/BRANCH_NAME)" >> $GITHUB_ENV

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
          token: ${{ steps.generate_github_token.outputs.token }}

      - name: Setting up authorization to NPM registry (.npmrc)
        run: |
          cat << EOF > "$HOME/.npmrc"
            provenance=true
            email=npmjs@commercetools.com
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publishing preview releases to npm registry
        run: |
          PREVIEW_TAG=$(echo "$BRANCH_NAME" | sed -e 's/^preview\///')
          pnpm changeset version --snapshot ${PREVIEW_TAG}
          pnpm changeset publish --tag ${PREVIEW_TAG}
          node ./scripts/update-npm-tag.mjs ${PREVIEW_TAG}
        env:
          GITHUB_TOKEN: ${{ steps.generate_github_token.outputs.token }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}

      - name: Post workflow result on PR as a comment
        if: always()
        run: |
          gh issue comment ${{ env.PR_NUMBER }} \
            --body "Release workflow ${{ job.status == 'success' && 'succeeded ✅' || 'failed ❌' }}\nSee details: [Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 